name: ci-e2e-lint

on:
  pull_request:
    paths:
      - "e2e/**"
      - "pnpm-lock.yaml"
      - ".github/workflows/ci-e2e-lint.yml"
      - "!**.md"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Setup pnpm workspace
        uses: ./.github/actions/setup-pnpm-workspace
      - name: Lint
        run: pnpm --filter e2e lint
