name: ci-packages-ui
on:
  pull_request:
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "packages/ui/**"
      - ".github/workflows/ci-packages-ui.yml"
      - ".github/actions/setup-pnpm-workspace/**"
      - "!**.md"

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: packages/ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup pnpm workspace
        uses: ./.github/actions/setup-pnpm-workspace
      - name: Lint
        run: pnpm lint

  build-storybook:
    name: build-storybook
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: packages/ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup pnpm workspace
        uses: ./.github/actions/setup-pnpm-workspace
      - name: Build Storybook
        run: pnpm build-storybook
